### ISSUE TITLE
colorWithHue: returns wrong result

### ISSUE THREAD

**Issue by tewha** [erica/uicolor-utilities#5]
`[UIColor colorWithHue: saturation: brightness: alpha:]` is a system function. This code overrides it with a function that returns a different result.

Example:

```
id green = [UIColor colorWithHue:0.231 saturation:0.786 brightness:0.669 alpha:1.000];
self.navigationController.navigationBar.tintColor = green;
```

Try this without UIColor-utilities and you'll get green. Try it while using UIColor-utilities, and UIColor-utilities will replace colorWithHue with one that returns red instead.

There's two bugs here:
1. Whatever logic UIColor-utilities uses to map HSB to RGB doesn't work. (I assume this affects code that serves a purpose, too.)
2. UIColor-utilities should not be replacing perfectly good system functions without reason.

**Comment by tewha** [comment]
I suspect the problem here is that UIColor-utilities is treating hue as a degree angle, whereas UIKit treats it as a fraction from 0-1.

**Comment by erica** [comment]
It predates that stuff and I haven't had a moment to update it.

-- E

**Comment by tewha** [comment]
This code seems to have been added in 2009, and colorWithHue dates to iOS 2.0.

https://github.com/erica/uicolor-utilities/commit/9a28215bf8b3dea2b67f6a413574ef5ff3a2786b
http://developer.apple.com/library/ios/#DOCUMENTATION/UIKit/Reference/UIColor_Class/Reference/Reference.html#//apple_ref/doc/uid/TP40006892-CH3-SW4

**Comment by erica** [comment]
Thanks for the heads up. I'll take a look when I get a chance and try to figure out what was going on.

-- E
