### ISSUE TITLE
64bit support would be great

### ISSUE THREAD

**Issue by ogezue** [erica/uicolor-utilities#8]
Is it planned to migrate to 64bit?

**Comment by erica** [comment]
I really should. Can you try kicking me in early January about it?

— E

**Comment by ogezue** [comment]
I’ll try my best ;)

Oliver

Von: Erica Sadun [mailto:notifications@github.com]
Gesendet: Dienstag, 10. Dezember 2013 19:46
An: erica/uicolor-utilities
Cc: Gepp, Oliver
Betreff: Re: [uicolor-utilities] 64bit support would be great (#8)

I really should. Can you try kicking me in early January about it?

— E

**Comment by erica** [comment]
Is there anything else that needs doing beyond what I did in January?

**Comment by ogezue** [comment]
Hi Erica - thanks for your fix! I will update my code in the next couple of days and give you feedback if there is anything else. Right now there is nothing to add. I'm sure my compiler will love your update!

Cheers Oliver

... Mobile Message

Am 11.02.2014 um 19:20 schrieb "Erica Sadun" <notifications@github.com<mailto:notifications@github.com>>:

Is there anything else that needs doing beyond what I did in January?

##

**Comment by erica** [comment]
If you can, also check out the new Mac app I added today to help search through the color dictionaries, convert to RGB, hex

**Comment by ogezue** [comment]
Hi Erica,

there are two compiler warnings in UIColor+HSV.m (unused function), but everything works fine.

Thanks for the update and the cocoapods integration.

Cheers, Oliver

Von: Erica Sadun [mailto:notifications@github.com]
Gesendet: Dienstag, 11. Februar 2014 19:31
An: erica/uicolor-utilities
Cc: Gepp, Oliver
Betreff: Re: [uicolor-utilities] 64bit support would be great (#8)

If you can, also check out the new Mac app I added today to help search through the color dictionaries, convert to RGB, hex

**Comment by erica** [comment]
I did not do cocoapods integration. And what is UIColor+HSV?

-- Erica

**Comment by ogezue** [comment]
I saw that the cocoapods has this source: https://github.com/fcanas/uicolor-utilities
I thought that it would be your code, if it is called like your project...

Cheers Oliver

---

Von: Erica Sadun notifications@github.com
Gesendet: Mittwoch, 19. Februar 2014 17:26
An: erica/uicolor-utilities
Cc: Gepp, Oliver
Betreff: Re: [uicolor-utilities] 64bit support would be great (#8)

I did not do cocoapods integration. And what is UIColor+HSV?

-- Erica

On Feb 19, 2014, at 8:34 AM, ogezue notifications@github.com wrote:

> Hi Erica,
> 
> there are two compiler warnings in UIColor+HSV.m (unused function), but everything works fine.
> 
> Thanks for the update and the cocoapods integration.
> 
> Cheers, Oliver
> 
> Von: Erica Sadun [mailto:notifications@github.com]
> Gesendet: Dienstag, 11. Februar 2014 19:31
> An: erica/uicolor-utilities
> Cc: Gepp, Oliver
> Betreff: Re: [uicolor-utilities] 64bit support would be great (#8)
> 
> If you can, also check out the new Mac app I added today to help search through the color dictionaries, convert to RGB, hex
> 
> On Feb 11, 2014, at 11:29 AM, ogezue <notifications@github.com<mailto:notifications@github.com>> wrote:
> 
> > Hi Erica - thanks for your fix! I will update my code in the next couple of days and give you feedback if there is anything else. Right now there is nothing to add. I'm sure my compiler will love your update!
> > 
> > Cheers Oliver
> > 
> > ... Mobile Message
> > 
> > Am 11.02.2014 um 19:20 schrieb "Erica Sadun" <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>>:
> > 
> > Is there anything else that needs doing beyond what I did in January?
> > 
> > ## 
> > 
> > ## Reply to this email directly or view it on GitHubhttps://github.com/erica/uicolor-utilities/issues/8#issuecomment-34785996.
> > 
> > Reply to this email directly or view it on GitHub.
> 
> ## 
> 
> ## Reply to this email directly or view it on GitHubhttps://github.com/erica/uicolor-utilities/issues/8#issuecomment-34787979.
> 
> Reply to this email directly or view it on GitHub.

##

**Comment by erica** [comment]
Looks like a fork! I'd recommend checking out both since I've been putting a lot of new features in

-- E
